version: "3"
services:
  angular9-app:
    build: .
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    command: npx ng serve --host 0.0.0.0 --poll=1000 --disable-host-check
