services:
  angular9-builder:
    build: .
    volumes:
      - ./dist:/app/dist
    entrypoint: sh
    command: -c "npx ng build --prod --base-href 'https://MatheusChiodi.github.io/Blog-with-Angular/'"
